import React from "react";
import {useSelector} from "react-redux";
import {ReducerState} from "../../redux";


const Home: React.FC = () => {
    const user = useSelector((state: ReducerState) => state.global.userInfo)
    return (
        <div>
            home
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
            <br />
            ...
            <br/>
            ...
        </div>
    );
};


export default Home;